// <auto-generated />
using System;
using JorgeMoncayoL_EjercicioCF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JorgeMoncayoL_EjercicioCF.Migrations
{
    [DbContext(typeof(JorgeMoncayoL_EjercicioCFContext))]
    [Migration("20231018135942_migrations")]
    partial class migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JorgeMoncayoL_EjercicioCF.Models.Burguer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("WithCheese")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Burguer");
                });

            modelBuilder.Entity("JorgeMoncayoL_EjercicioCF.Models.Promo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BurguerId")
                        .HasColumnType("int");

                    b.Property<string>("PromoDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromoId")
                        .HasColumnType("int");

                    b.Property<string>("PromoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BurguerId");

                    b.ToTable("Promo");
                });

            modelBuilder.Entity("JorgeMoncayoL_EjercicioCF.Models.Promo", b =>
                {
                    b.HasOne("JorgeMoncayoL_EjercicioCF.Models.Burguer", "Burguer")
                        .WithMany("Promo")
                        .HasForeignKey("BurguerId");

                    b.Navigation("Burguer");
                });

            modelBuilder.Entity("JorgeMoncayoL_EjercicioCF.Models.Burguer", b =>
                {
                    b.Navigation("Promo");
                });
#pragma warning restore 612, 618
        }
    }
}
